# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.6.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
import pandas as pd
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
import tensorflow as tf
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
# categorical output
# ann.add(tf.keras.layers.Dense(units=1,activation='softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# categorical output
# ann.compile(optimizer='adam',loss='catgorical_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 662us/step - loss: 0.5797 - accuracy: 0.7221
Epoch 2/100
250/250 [==============================] - 0s 669us/step - loss: 0.4599 - accuracy: 0.7956
Epoch 3/100
250/250 [==============================] - 0s 622us/step - loss: 0.4405 - accuracy: 0.8016
Epoch 4/100
250/250 [==============================] - 0s 529us/step - loss: 0.4326 - accuracy: 0.8066
Epoch 5/100
250/250 [==============================] - 0s 501us/step - loss: 0.4278 - accuracy: 0.8126
Epoch 6/100
250/250 [==============================] - 0s 531us/step - loss: 0.4234 - accuracy: 0.8174
Epoch 7/100
250/250 [==============================] - 0s 621us/step - loss: 0.4192 - accuracy: 0.8216
Epoch 8/100
250/250 [==============================] - 0s 449us/step - loss: 0.4144 - accuracy: 0.8235
Epoch 9/100
250/250 [==============================] - 0s 538us/step - loss: 0.4097 - accuracy: 0.8273
Epoch 10/100
250/250 [==============================] - 0s 517us/step - l

250/250 [==============================] - 0s 543us/step - loss: 0.3315 - accuracy: 0.8645
Epoch 80/100
250/250 [==============================] - 0s 517us/step - loss: 0.3314 - accuracy: 0.8640
Epoch 81/100
250/250 [==============================] - 0s 501us/step - loss: 0.3313 - accuracy: 0.8654
Epoch 82/100
250/250 [==============================] - 0s 529us/step - loss: 0.3316 - accuracy: 0.8641
Epoch 83/100
250/250 [==============================] - 0s 473us/step - loss: 0.3313 - accuracy: 0.8645
Epoch 84/100
250/250 [==============================] - 0s 525us/step - loss: 0.3316 - accuracy: 0.8645
Epoch 85/100
250/250 [==============================] - 0s 517us/step - loss: 0.3313 - accuracy: 0.8639
Epoch 86/100
250/250 [==============================] - 0s 502us/step - loss: 0.3311 - accuracy: 0.8640
Epoch 87/100
250/250 [==============================] - 0s 525us/step - loss: 0.3312 - accuracy: 0.8644
Epoch 88/100
250/250 [==============================] - 0s 537us/step - loss:

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [26]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,50000]])))

[[0.13697329]]


In [25]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,50000]]))>0.5)

[[False]]


### Predicting the Test set results

In [21]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1538   57]
 [ 291  114]]


0.826