In [7]:
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()
X, y = iris.data[:, 1:3], iris.target

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [9]:
from sklearn.ensemble import BaggingClassifier
from sklearn import tree
model= BaggingClassifier(tree.DecisionTreeClassifier(random_state=1))
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.8947368421052632

In [10]:
from sklearn.ensemble import BaggingRegressor
from sklearn import tree
model= BaggingRegressor(tree.DecisionTreeRegressor(random_state=1))
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.8999024390243903

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.metrics import accuracy_score
model=RandomForestClassifier()

model.fit(X_train,y_train)
print('Number of trees: ',model.n_estimators)

Number of trees:  100


Predicting and Accuracy on Train Data

In [13]:
predict_train=model.predict(X_train)
print('\n Target on train data',predict_train)


 Target on train data [1 1 2 0 2 0 0 1 2 2 2 2 1 2 1 1 2 2 2 2 1 2 1 0 2 1 1 1 1 2 0 0 2 1 0 0 1
 0 2 1 0 1 2 1 0 2 2 2 2 0 0 2 2 0 2 0 2 2 0 0 2 0 0 0 1 2 2 0 0 0 1 1 0 0
 1 0 2 1 2 1 0 2 0 2 0 0 2 0 2 1 1 1 2 2 1 1 0 1 2 2 0 1 1 1 1 0 0 0 2 1 2
 0]


In [14]:
accuracy_train=accuracy_score(y_train,predict_train)
print('\nAccuracy score on train data:',accuracy_train)


Accuracy score on train data: 1.0


Predict and Accuracy on Test Data

In [15]:
predict_test=model.predict(X_test)
print('\nTarget on test data',predict_test)


Target on test data [2 1 0 2 0 2 0 1 2 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 1 2 1 0
 2]


In [16]:
accuracy_test=accuracy_score(y_test,predict_test)
print('\nAccuracy score on train data:',accuracy_test)


Accuracy score on train data: 0.9210526315789473


AdaBoostClassifier

In [22]:
from sklearn.ensemble import AdaBoostClassifier

ada_boost_clf= AdaBoostClassifier(n_estimators=30)
ada_boost_clf.fit(X_train,y_train)
y_pred=ada_boost_clf.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(round(accuracy_score(y_test,y_pred),2))

[[13  0  0]
 [ 0 15  1]
 [ 0  8  1]]
0.76


In [25]:
#print(f"Classification Report:\n{clf_report}")

In [29]:
from sklearn.ensemble import GradientBoostingRegressor
model=GradientBoostingRegressor(learning_rate=0.01,random_state=1)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.7740288474183609

In [30]:
import xgboost as xgb
model=xgb.XGBRegressor(random_state=1,learning_rate=0.01)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.7645140258285515

In [31]:
model=xgb.XGBClassifier(random_state=1,learning_rate=0.01)
model.fit(X_train,y_train)
model.score(X_test,y_test)

[15:27:03] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\komajha\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


0.8947368421052632

In [33]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [34]:
grid_search=GridSearchCV(RandomForestClassifier(random_state=0),
{
    'n_estimators':np.arange(5,100,5),
    'max_features':np.arange(0.1,1.0,0.05),
},cv=5, scoring="r2",verbose=1,n_jobs=-1)


In [35]:
grid_search.fit(X_train,y_train)

Fitting 5 folds for each of 342 candidates, totalling 1710 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=0), n_jobs=-1,
             param_grid={'max_features': array([0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 ,
       0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95]),
                         'n_estimators': array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])},
             scoring='r2', verbose=1)

In [36]:
grid_search.best_score_

0.9482522796352584

In [37]:
X_train

array([[3. , 4.2],
       [2.6, 4. ],
       [3. , 5.5],
       [3.2, 1.3],
       [3.1, 5.1],
       [3.5, 1.6],
       [3.7, 1.5],
       [2. , 3.5],
       [3. , 5.5],
       [3.3, 5.7],
       [2.2, 5. ],
       [2.5, 5.8],
       [2.5, 3.9],
       [3. , 6.1],
       [3.3, 4.7],
       [2.4, 3.8],
       [2.7, 4.9],
       [2.8, 5.1],
       [2.5, 4.5],
       [2.5, 5. ],
       [3.2, 4.7],
       [3. , 5.2],
       [3.4, 4.5],
       [3.1, 1.6],
       [2.7, 5.1],
       [2.7, 4.2],
       [2.9, 3.6],
       [2.5, 4. ],
       [3. , 4.6],
       [3.2, 6. ],
       [3.7, 1.5],
       [3. , 1.1],
       [2.7, 5.3],
       [3. , 4.2],
       [3.4, 1.7],
       [4.4, 1.5],
       [3.1, 4.9],
       [3.1, 1.5],
       [3. , 5.1],
       [2.5, 3. ],
       [3.4, 1.4],
       [2.2, 4.5],
       [3.6, 6.1],
       [2.9, 4.2],
       [3. , 1.4],
       [3. , 5.9],
       [3.2, 5.7],
       [3. , 5.8],
       [2.8, 5.6],
       [3.8, 1.6],
       [3.4, 1.6],
       [3.2, 5.1],
       [3.3,

In [38]:
y_train

array([1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2,
       1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1,
       0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 2,
       2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 0,
       2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1,
       2, 0])

In [39]:
type(X_train)

numpy.ndarray

In [40]:
type(y_train)

numpy.ndarray