In [148]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings 
import seaborn as sns
warnings.filterwarnings('ignore')

In [165]:
from sklearn import datasets
iris=datasets.load_iris()
X,y=iris.data[:,1:3],iris.target

In [166]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=45)

In [167]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Bagging for DecisionTreeClassifier

In [168]:
from sklearn.ensemble import BaggingClassifier
from sklearn import tree
model=BaggingClassifier(tree.DecisionTreeClassifier(random_state=1))
model.fit(X_train,y_train)
model.fit(X_test,y_test)

BaggingClassifier(base_estimator=DecisionTreeClassifier(random_state=1))

# Bagging for DecisionTreeRegressor

In [169]:
from sklearn.ensemble import BaggingClassifier
from sklearn import tree
model=BaggingClassifier(tree.DecisionTreeRegressor(random_state=1))
model.fit(X_train,y_train)
model.fit(X_test,y_test)

BaggingClassifier(base_estimator=DecisionTreeRegressor(random_state=1))

# Random forest Classifier

In [170]:
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier()

model.fit(X_train,y_train)

print('Number of trees used: ',model.n_estimators)

predict_train=model.predict(X_train)
print('\nTarget on train data ')
print(predict_train)

accuracy_train=accuracy_score(y_train,predict_train)
print('\naccuracy score on train dataset: ',accuracy_train)

predict_test=model.predict(X_test)
print('\nTarget on train data ')
print(predict_test)

accuracy_test=accuracy_score(y_test,predict_test)
print('\naccuracy score on test dataset: ',accuracy_test)

Number of trees used:  100

Target on train data 
[2 1 2 2 0 2 0 0 1 0 0 1 0 1 1 0 2 1 2 0 0 1 2 0 2 0 0 1 0 1 1 2 1 2 0 0 0
 0 1 0 1 2 1 1 1 0 0 2 0 1 2 2 2 1 1 2 1 0 1 1 1 2 1 1 2 1 1 2 2 2 0 0 1 2
 2 2 0 1 2 1 1 1 0 2 2 0 0 2 0 2 1 1 2 2 1 0 0 2 0 1 2 2 0 0 0 2 0 0 2 1 1
 1 0 2 2 1 1 0 2 2]

accuracy score on train dataset:  0.9833333333333333

Target on train data 
[0 0 2 0 0 0 0 2 2 2 0 2 2 2 2 0 2 2 0 1 1 2 2 1 0 2 1 1 0 1]

accuracy score on test dataset:  0.9666666666666667


# AdaBoostClassifier

In [171]:
from sklearn.ensemble import AdaBoostClassifier
ada_boost_clf=AdaBoostClassifier(n_estimators=30)
ada_boost_clf.fit(X_train,y_train)
pred_test=ada_boost_clf.predict(X_test)
pred_train=ada_boost_clf.predict(X_train)
print(confusion_matrix(y_test,pred_test))
print(round(accuracy_score(y_test,pred_test),2))
print(round(accuracy_score(y_train,pred_train),2))

[[11  0  0]
 [ 0  7  0]
 [ 0 11  1]]
0.63
0.71


In [172]:
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier(learning_rate=0.01,random_state=1)
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [173]:
from sklearn.ensemble import GradientBoostingRegressor
model=GradientBoostingRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9804786225324751

In [174]:
!pip install xgboost
import xgboost as xgb
model=xgb.XGBClassifier(random_state=1,learning_rate=0.01)
model.fit(X_train,y_train)
model.score(X_test,y_test)

[16:02:48] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


1.0

In [175]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

In [176]:
grid_search=GridSearchCV(RandomForestClassifier(random_state=0),
    {
    'n_estimator':np.arange(5,100,5),
    'max_features':np.arange(0.1,1.0,0.05)
},cv=5,scoring='r2',verbose=1,n_jobs=-1)
grid_search.fit(X_train,y_train)

Fitting 5 folds for each of 342 candidates, totalling 1710 fits


ValueError: Invalid parameter n_estimator for estimator RandomForestClassifier(max_features=0.1, random_state=0). Check the list of available parameters with `estimator.get_params().keys()`.

In [177]:
grid_search.best_estimator_

AttributeError: 'GridSearchCV' object has no attribute 'best_estimator_'

In [138]:
grid_search.best_score_

AttributeError: 'GridSearchCV' object has no attribute 'best_score_'