In [15]:
import pandas as pd
import numpy as np

In [24]:
df=pd.read_csv('file.tsv',sep='\t',names=['user_id','item_id','rating','timestamp'])
df.head()

user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

In [19]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0] 
n_movies = df.item_id.unique().shape[0]

train_data, test_data = train_test_split(df, test_size=0.25)

In [20]:
train_data_matrix = np.zeros((n_users, n_movies))
for line in train_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    train_data_matrix[line[1]-1, line[2]-1] = line[3] 
train_data_matrix
  

array([[0., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix


array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:, np.newaxis] 
ratings_diff = (train_data_matrix - mean_user_rating) 
user_pred = mean_user_rating + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.58171519,  0.54349909,  0.44861177, ...,  0.27343903,
         0.27336019,  0.27094057],
       [ 1.30841453,  0.27355117,  0.14000031, ..., -0.06204983,
        -0.06090296, -0.06403535],
       [ 1.34524367,  0.24316197,  0.11969539, ..., -0.08827809,
        -0.08677758, -0.08994921],
       ...,
       [ 1.37188903,  0.30289512,  0.19654765, ..., -0.00636525,
        -0.00557789, -0.00846347],
       [ 1.41814319,  0.3760327 ,  0.29174408, ...,  0.11240996,
         0.11228316,  0.1099032 ],
       [ 1.20890752,  0.15524892,  0.04606679, ..., -0.15630296,
        -0.15562321, -0.15859762]])