In [52]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
df=pd.read_csv('seeds.csv')

In [53]:
df.head()

Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
0  15.26      14.84       0.8710          5.763         3.312   
1  14.88      14.57       0.8811          5.554         3.333   
2  14.29      14.09       0.9050          5.291         3.337   
3  13.84      13.94       0.8955          5.324         3.379   
4  16.14      14.99       0.9034          5.658         3.562   

   Asymmetry.Coeff  Kernel.Groove  Type  
0            2.221          5.220     1  
1            1.018          4.956     1  
2            2.699          4.825     1  
3            2.259          4.805     1  
4            1.355          5.175     1

In [54]:
df.isnull().sum()

Area               0
Perimeter          0
Compactness        0
Kernel.Length      0
Kernel.Width       0
Asymmetry.Coeff    0
Kernel.Groove      0
Type               0
dtype: int64

In [55]:
X=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values

In [56]:
X.shape

(199, 6)

In [57]:
y.shape

(199,)

In [58]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [59]:
def derivatives_sigmoid(x):
    return x*(1-x)

In [60]:
epoch=500
lr=0.1
inputlayer_neurons=6
outputlayer_neurons=199
hiddenlayer_neurons=int(2/3*inputlayer_neurons+outputlayer_neurons)

In [61]:
# weight and bias initialisation
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,outputlayer_neurons))
bout=np.random.uniform(size=(1,outputlayer_neurons))
print(wh,bh,wout,bout)

[[0.58759181 0.01948687 0.83213617 ... 0.29568741 0.29931978 0.43032071]
 [0.64466196 0.81618585 0.8168055  ... 0.53887667 0.87762205 0.18423274]
 [0.9196851  0.87813722 0.75599287 ... 0.50234442 0.54092057 0.07525814]
 [0.12842677 0.26418404 0.50076967 ... 0.70411801 0.73217216 0.87333184]
 [0.19289634 0.38132001 0.93241202 ... 0.99596015 0.64463199 0.84816455]
 [0.76650711 0.36612554 0.39245139 ... 0.2363903  0.93521467 0.46254616]] [[0.49638493 0.63017682 0.51526491 0.25062923 0.83788218 0.2431603
  0.01995217 0.55034003 0.48462325 0.37166842 0.98404579 0.25683719
  0.44714696 0.79535871 0.65352387 0.19569171 0.93141627 0.6427701
  0.28232004 0.78960226 0.32354253 0.36109295 0.95391703 0.99702251
  0.28616908 0.31345185 0.52325053 0.67498676 0.34595428 0.55099357
  0.23245995 0.75106952 0.34130282 0.18160318 0.58023929 0.58503749
  0.67485123 0.68493541 0.66079426 0.80026114 0.32297332 0.00360069
  0.99188684 0.79116421 0.77678131 0.30969472 0.50524313 0.26971716
  0.88069845 0.0944

In [62]:
for i in range(epoch):
    # forward propagation
    hinp1=np.dot(X,wh)
    hinp=hinp1 + bh
    hlayer_act = sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp= outinp1+ bout
    output = sigmoid(outinp)
    # backward propagation
    EO = y-output
    outgrad = derivatives_sigmoid(output)
    d_output = EO* outgrad
    EH = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act)#how much hidden layer wts contributed to error
    d_hiddenlayer = EH * hiddengrad
    wout += hlayer_act.T.dot(d_output) *lr# dotproduct of nextlayererror and currentlayerop
    # bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    #bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

In [63]:
type(y)

numpy.ndarray

In [64]:
type(output)

numpy.ndarray

In [65]:
output.shape

(199, 199)

In [66]:
print("Input: ",X)
print("Actual Output: ",y)
print("Predicted Output: ",output)

Input:  [[14.84    0.871   5.763   3.312   2.221   5.22  ]
 [14.57    0.8811  5.554   3.333   1.018   4.956 ]
 [14.09    0.905   5.291   3.337   2.699   4.825 ]
 ...
 [13.66    0.8883  5.236   3.232   8.315   5.056 ]
 [13.21    0.8521  5.175   2.836   3.598   5.044 ]
 [13.34    0.8684  5.243   2.974   5.637   5.063 ]]
Actual Output:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
Predicted Output:  [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [67]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y,output[0])
print(cm)
accuracy_score(y,output[0])

[[66  0  0]
 [68  0  0]
 [65  0  0]]


0.3316582914572864

The number of hidden neurons should be between the size of the input layer and the size of the output layer.
\
The number of hidden neurons should be 2/3 the size of the input layer, plus the size of the output layer.
\
The number of hidden neurons should be less than twice the size of the input layer
