# Tensorflow

#GPU
\
!pip install tensorflow-gpu==2.0.0
\
#CPU
\
!pip install tensorflow==2.0.0
\
#Upgrade to the latest Version
\
! pip install - upgrade tensorflow
\
#checking the installation 
\
import tensorflow as tf
\
print(tf.__version__)

For all the hidden layers we use "Relu" as an activation function. Relu= max(0,X)
\
if it is binary classifiation we use "sigmoid" as an activation function
\
if it is multi class classification we use "softmax" as activation function
\
predict_proba gives the description of probality

epoch is a hyper parameter. If epoch is 1 then one forward and one backward operation is done

# Tensorflow Hands On

In [1]:
# Current stable release for CPU and GPU of tensor flow
!pip install tensorflow

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.6.1'

In [4]:
#The constant are immutable
A=tf.constant([[4,3],[6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]])>

In [7]:
# variables are mutable
V=tf.Variable([[4,3],[6,1]])
V

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[4, 3],
       [6, 1]])>

In [12]:
# concatination
tf_concat=tf.concat(values=[A,V],axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 4, 3],
       [6, 1, 6, 1]])>

In [21]:
# concatination
tf_concat=tf.concat(values=[A,V],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [4, 3],
       [6, 1]])>

In [17]:
# array with zeros in int type
tf_zeros=tf.zeros(shape=[3,4],dtype=tf.int32)
tfzeros

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [19]:
# array with  ones in float type
tf_ones=tf.ones(shape=[3,4],dtype=tf.float32)
tfones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [24]:
# array with random values
tf_rand=tf.random.uniform(shape=[3,4],minval=4,maxval=10,dtype=tf.int32)
tf_rand

In [30]:
# reshape 
tf_reshape=tf.reshape(tensor=tf_rand,shape=[1,12])
tf_reshape

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[5, 7, 6, 4, 5, 7, 8, 6, 7, 6, 8, 7]])>

In [40]:
# transpose
tf_trans=tf.transpose(tf_reshape)
tf_trans

<tf.Tensor: shape=(12, 1), dtype=int32, numpy=
array([[5],
       [7],
       [6],
       [4],
       [5],
       [7],
       [8],
       [6],
       [7],
       [6],
       [8],
       [7]])>

In [39]:
# identity matrix
tf_identity=tf.eye(num_rows=3,num_columns=5)
tf_identity

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>

In [42]:
# prints the no of rows and cols
row,col=tf_identity.shape
print(row,col)

3 5


In [43]:
# matrix multiplication
A=tf.constant([[4,3],[6,1]])
B=tf.constant([[3,1],[5,4]])
AB=tf.matmul(A,B)
AB

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 16],
       [23, 10]])>

In [44]:
# multiplies the rows and cols
AB_mul=tf.multiply(A,B)
AB_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  3],
       [30,  4]])>

In [45]:
# multiplies the each value in A with three
# element wise multiplication
A*3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  9],
       [18,  3]])>

In [63]:
A=tf.constant([[4.1,3.2],[6.3,1.4]])
my_var=tf.Variable(A)
bool_var=tf.Variable([False,False,True])
complex_var=tf.Variable([2+4j,6+3j])

In [64]:
print("shape: ",bool_var.shape)
print("Dtype: ",bool_var.dtype)

shape:  (3,)
Dtype:  <dtype: 'bool'>


In [65]:
print("shape: ",complex_var.shape)
print("Dtype: ",complex_var.dtype)

shape:  (2,)
Dtype:  <dtype: 'complex128'>


In [66]:
tf.reshape(var,[4,1])

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[4.1],
       [3.2],
       [6.3],
       [1.4]], dtype=float32)>

In [70]:
# the == is with the variable not with the names
a=tf.Variable(my_var,name="john")
b=tf.Variable(my_var,name="john1")
print(a==b)

tf.Tensor(
[[ True  True]
 [ True  True]], shape=(2, 2), dtype=bool)


In [73]:
# sparse tensor
tf_sparse=tf.sparse.SparseTensor(indices=[[0,0],[1,2]],values=[3,4],dense_shape=[3,4])
print(tf_sparse)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([3 4], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [75]:
# place Holders
x=tf.placeholders(tf.float32)
x

AttributeError: module 'tensorflow' has no attribute 'placeHolders'

In [76]:
# Define a Python function.
def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# `a_function_that_uses_a_graph` is a TensorFlow `Function`.
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Make some tensors.
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
# Call a `Function` like a Python function.
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()
assert(orig_value == tf_function_value)